#!/usr/bin/bash

#devcheck - /dev consistency check.
#Copyright (C) 2019 Nathan Torchia <nemasu@gmail.com>
#
#This library is free software; you can redistribute it and/or
#modify it under the terms of the GNU Lesser General Public
#License as published by the Free Software Foundation; either
#version 2.1 of the License, or (at your option) any later version.
#
#This library is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#Lesser General Public License for more details.
#
#You should have received a copy of the GNU Lesser General Public
#License along with this library; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

declare -A dblist
declare -A fslist

function read_fs_list() {
    IFS=$'\n'
    pushd "$1" &> /dev/null
    for i in `find -type b -or -type c`; do
        fslist[$i]=1
    done
    popd &> /dev/null
}
function read_db_list() {
    IFS=$'\n'
    for i in `cat "$1"`; do
        dblist[$i]=1
    done
}

#Usage: <file_listing>
function check() {

    read_fs_list /dev
    read_db_list $1

    #Size check
    if [ ${#dblist[*]} -ne ${#fslist[*]} ]; then
        echo "Error: Size does not match, exiting."
        echo "DB: ${#dblist[*]}"
        echo "FS: ${#fslist[*]}"
        exit 1
    fi

    #File check
    for k in "${!dblist[@]}"; do
        if [ "${fslist[$k]}" != "${dblist[$k]}" ]; then
            echo "Error, missmatched list for file $k"
            echo "FS: ${!fslist[$k]}"
            echo "DB: ${!dblist[$k]}"
            exit 1
        fi
    done
}

#Usage: <directory>
function dump() {
    pushd /dev &> /dev/null
    find -type b -or -type c
    popd &> /dev/null
}

if [ "$1" == "-dump" ]; then
    dump
    exit 0
fi

if [ "$1" == "-check" ]; then
    shift
    check $1
    exit 0
fi

echo "Invalid option, example usage:"
echo "devcheck -dump > dev.list"
echo "devcheck -check dev.list"

exit 0
